include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/cli11/cli11.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/clipper2/clipper2.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/cpputility/cpputility.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/curl/curl.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/freetype/freetype.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/glad/glad.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/glfw/glfw.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/glm/glm.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/imgui/docking.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/implot/implot.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/json/nlohmann.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/nfd/nfd.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/opencv/opencv.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/sqlite/sqlite.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/talib/talib.cmake")